name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'  # Spécifiez la version de Python 3.7

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Si PyInstaller est dans requirements.txt, cette étape n'est pas nécessaire
    # Sinon, ajoutez cette étape
    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build with PyInstaller
      run: python build_windows.py

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: seedkeeper-windows
        path: dist/seedkeeper_tool.exe
