name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'  # Spécifiez la version de Python 3.7

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python -m unittest discover tests  # Ajustez ou commentez cette ligne si vous n'avez pas de tests

    - name: Build with PyInstaller
      run: pyinstaller --onefile seedkeeper_tool.py  # Ajustez selon votre configuration

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: seedkeeper-windows
        path: dist/seedkeeper_tool.exe
