name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'

    - name: Install system dependencies (Windows)
      run: |
        choco install -y swig
        choco install -y imagemagick

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        pip install pyscard || echo "Failed to install pyscard"

    - name: Verify Python dependencies
      run: |
        python -c "import sys; print('Python version:', sys.version)"
        python -c "import PIL; print('Pillow version:', PIL.__version__)"
        python -c "import tkinter; print('Tkinter is installed')"
        python -c "import cryptography; print('Cryptography version:', cryptography.__version__)"
        python -c "import ecdsa; print('ECDSA version:', ecdsa.__version__)"
        python -c "import mnemonic; print('Mnemonic is installed')"
        python -c "import pyscard; print('PyScard is installed')" || echo "PyScard is not installed"
        python -c "import customtkinter; print('CustomTkinter version:', customtkinter.__version__)"
        python -c "import pyaes; print('PyAES is installed')"
        python -c "import pycparser; print('pycparser version:', pycparser.__version__)"

    - name: Build executable (Windows)
      run: python build_windows.py

    - name: Upload artifact (Windows)
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: seedkeeper-windows
        path: dist/seedkeeper_tool.exe
