name: Building Seedkeeper Tool Windows Binary

on:
  push:
    tags: '*'
    branches: [ main, dev, test_* ]
  pull_request:
    branches: [ main ]

jobs:
  build_windows:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed --icon=satochip_utils.ico seedkeeper_tool.py

    - name: Archive Windows binary
      uses: actions/upload-artifact@v4
      with:
        name: seedkeeper-tool-windows
        path: dist/seedkeeper_tool.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/seedkeeper_tool.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}